#!/bin/bash
# ============================================
# RESUMEN DE INSTALACIÓN - nl360.site
# ============================================

echo "=========================================="
echo "   🎉 INSTALACIÓN COMPLETADA CON ÉXITO"
echo "=========================================="
echo ""

echo "📍 SERVICIOS INSTALADOS:"
echo ""
echo "✅ N8N (Automatización de Workflows)"
echo "   URL: https://automata.nl360.site"
echo "   Puerto interno: 5678"
echo "   SSL: ✅ Habilitado"
echo ""

echo "✅ WordPress Multisite"
echo "   URL principal: https://nl360.site"
echo "   Wildcard: https://*.nl360.site"
echo "   Puerto interno: 8000"
echo "   SSL: ✅ Habilitado"
echo ""

echo "✅ phpMyAdmin"
echo "   URL: https://db.nl360.site"
echo "   Puerto interno: 8080"
echo "   SSL: ✅ Habilitado"
echo "   Usuario root: root"
echo "   Password: Ver /opt/docker-apps/.env"
echo ""

echo "✅ Filebrowser (Gestor de archivos web)"
echo "   URL: https://files.nl360.site"
echo "   Puerto interno: 8081"
echo "   SSL: ✅ Habilitado"
echo "   Usuario inicial: admin"
echo "   Password inicial: admin (¡Cambiar inmediatamente!)"
echo ""

echo "✅ MySQL 8.0"
echo "   Puerto: 3306"
echo "   Base de datos: wordpress"
echo "   Credenciales: Ver /opt/docker-apps/.env"
echo ""

echo "=========================================="
echo "📁 ESTRUCTURA DE ARCHIVOS:"
echo "=========================================="
echo ""
echo "/opt/docker-apps/"
echo "├── docker-compose.yml    (Configuración de contenedores)"
echo "├── .env                  (Variables de entorno y contraseñas)"
echo "├── n8n/                  (Datos de N8N)"
echo "├── wordpress/            (Archivos de WordPress)"
echo "├── mysql/                (Base de datos MySQL)"
echo "├── phpmyadmin/           (Configuración phpMyAdmin)"
echo "└── filebrowser/          (Configuración Filebrowser)"
echo ""

echo "=========================================="
echo "🔧 COMANDOS ÚTILES:"
echo "=========================================="
echo ""
echo "Ver estado de contenedores:"
echo "  docker ps"
echo ""
echo "Ver logs de un servicio:"
echo "  docker logs wordpress"
echo "  docker logs n8n"
echo "  docker logs mysql_db"
echo ""
echo "Detener todos los servicios:"
echo "  cd /opt/docker-apps && docker compose down"
echo ""
echo "Iniciar todos los servicios:"
echo "  cd /opt/docker-apps && docker compose up -d"
echo ""
echo "Reiniciar un servicio específico:"
echo "  docker restart wordpress"
echo "  docker restart n8n"
echo ""
echo "Recargar Nginx:"
echo "  sudo systemctl reload nginx"
echo ""
echo "Ver certificados SSL:"
echo "  sudo certbot certificates"
echo ""

echo "=========================================="
echo "🔐 ACCESO SFTP:"
echo "=========================================="
echo ""
echo "Host: $(curl -s ifconfig.me || hostname -I | awk '{print $1}')"
echo "Puerto: 22"
echo "Usuario: root (o tu usuario SSH)"
echo "Directorio principal: /opt/docker-apps/"
echo ""

echo "=========================================="
echo "⚠️  SIGUIENTES PASOS IMPORTANTES:"
echo "=========================================="
echo ""
echo "1. 🔒 CAMBIAR CONTRASEÑAS:"
echo "   - Editar /opt/docker-apps/.env"
echo "   - Cambiar password de Filebrowser (admin/admin)"
echo ""
echo "2. 🌐 CONFIGURAR WORDPRESS MULTISITE:"
echo "   - Visitar https://nl360.site"
echo "   - Completar instalación de WordPress"
echo "   - Activar red multisite desde wp-admin"
echo ""
echo "3. 🤖 CONFIGURAR N8N:"
echo "   - Visitar https://automata.nl360.site"
echo "   - Crear cuenta de administrador"
echo "   - Importar tus +100 workflows"
echo ""
echo "4. 📊 VERIFICAR PHPMYADMIN:"
echo "   - Visitar https://db.nl360.site"
echo "   - Iniciar sesión con credenciales de MySQL"
echo ""
echo "5. 📁 PROBAR FILEBROWSER:"
echo "   - Visitar https://files.nl360.site"
echo "   - Login: admin / admin"
echo "   - ⚠️  CAMBIAR PASSWORD INMEDIATAMENTE"
echo ""
echo "6. 🔄 BACKUPS:"
echo "   - Configurar backup de /opt/docker-apps/"
echo "   - Especialmente: n8n/, wordpress/, mysql/"
echo ""

echo "=========================================="
echo "📋 INFORMACIÓN DEL SISTEMA:"
echo "=========================================="
docker --version
docker compose version
nginx -v 2>&1
certbot --version
echo ""
echo "Contenedores activos:"
docker ps --format "  - {{.Names}} ({{.Status}})"
echo ""
echo "Espacio en disco:"
df -h / | tail -1
echo ""

echo "=========================================="
echo "✨ ¡Todo listo! Tu VPS está configurado."
echo "=========================================="
